### ISSUE TITLE
Firmware directory changed in new M binaries

### ISSUE THREAD

**Issue by rancidfrog** [SuperBenevolent/aosp-vendor-qcom-proprietary-firmware#3]
Just to be aware,
Directory changed from:
```
$(call inherit-product-if-exists, vendor/qcom/proprietary/firmware/qcom-modem-firmware.mk)
```
Whereas now it is:
```
$(call inherit-product-if-exists, vendor/qcom/firmware/qcom-modem-firmware.mk)
```
Moved from **proprietary/firmware** to just **firmware**.
Change needed in local Manifest: project path="vendor/qcom/firmware"

**Comment by AdFad666** [comment]
Thanks, I'll rename accordingly.

**Comment by rancidfrog** [comment]
Are any other changes needed?
As I made the change but still modem not detected, I get No SIM card:
`[   35.246064] pil-q6v5-mss fc880000.qcom,mss: modem: loading from 0x08000000 to 0x0cf00000
[   35.247255] M-Notify: General: 6
[   35.252281] pil-q6v5-mss fc880000.qcom,mss: Failed to locate mba.b00
[   35.257593] pil-q6v5-mss fc880000.qcom,mss: modem: Invalid firmware metadata
[   35.264756] M-Notify: General: 5
[   35.267894] smd_pkt_open failed on smd_pkt_dev id:0 - subsystem_get failed for modem
[   35.275934] M-Notify: General: 7
`
